### ISSUE TITLE
Add --unset flag to the shipyard env command

### ISSUE THREAD

**Issue by gregoryhunt** [shipyard-run/shipyard#117]
Add --unset flag to the shipyard env command to allow for easy unsetting of environment variables.

shipyard env creates the command in while you can evaluate to export the shipyard outputs as environment variables.

shipyard env --unset should create the command to unset or clear the outputs and should directly undo the shipyard env command

**Comment by nicholasjackson** [comment]
This is a great idea @gregoryhunt, should also be quite simple to implement. 

The code where this is implemented can be found in the following file: https://github.com/shipyard-run/shipyard/blob/main/cmd/env.go

We use Cobra for the CLI so adding a flag should be pretty straightforward, you could then use that flag to flip the prefix on line 43 from "export" to unset". I am not sure about the unset command for windows.

https://github.com/shipyard-run/shipyard/blob/0d2152b0bf0c5e6d910dc6664cbd4ee5e0e1fea0/cmd/env.go#L43

Happy to accept a PR if you would like to give this a go?
