### ISSUE TITLE
checksums.txt for v0.4.11 includes only a checksum for windows x86_64

### ISSUE THREAD

**Issue by suzuki-shunsuke** [shipyard-run/shipyard#181]
**Describe the bug**

https://github.com/shipyard-run/shipyard/releases/download/v0.4.11/checksums.txt includes only a checksum for windows x86_64.

```
04ff87a7751af0f732d1fc1647413b1b14083318bff1d959c4d1715541cae79f  shipyard_0.4.11_windows_x86_64.zip
```

**To Reproduce**

**Expected behavior**

Checksums for all assets are included in `checksums.txt`.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

- https://github.com/aquaproj/aqua-registry/pull/6743
  - CI failed due to this issue

**Comment by suzuki-shunsuke** [comment]
I've created a pull request to solve this issue. https://github.com/shipyard-run/shipyard/pull/182

**Comment by suzuki-shunsuke** [comment]
- :o: https://github.com/shipyard-run/shipyard/releases/download/v0.3.18/checksums.txt
- :x: https://github.com/shipyard-run/shipyard/releases/download/v0.3.20/checksums.txt

https://github.com/shipyard-run/shipyard/compare/v0.3.18...v0.3.20

This pull request and commit include this bug.

https://github.com/shipyard-run/shipyard/commit/90bdc7487b18c1a9ece4fbb172f1b149dac3df3d
https://github.com/shipyard-run/shipyard/pull/130

**Comment by nicholasjackson** [comment]
Thank you so much @suzuki-shunsuke this has all been merged and a new release is currently building.

Nic
