### ISSUE TITLE
"Error parsing README.md front: unknown delim"

### ISSUE THREAD

**Issue by Wolfsrudel** [shipyard-run/shipyard#66]
I am following the guide at https://learn.hashicorp.com/consul/gs-consul-service-mesh/understand-consul-service-mesh#setup-a-kubernetes-environment-with-shipyard getting the following error. :(

```
curl https://shipyard.run/apply | \
 bash -s github.com/shipyard-run/blueprints//learn-consul-service-mesh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   315  100   315    0     0     77      0  0:00:04  0:00:04 --:--:--    77
Running configuration from:  github.com/shipyard-run/blueprints//learn-consul-service-mesh

Error parsing README.md front: unknown delim
2020-06-05T12:52:27.182+0200 [DEBUG] Statefile does not exist
```

**Comment by nicholasjackson** [comment]
Hi @Wolfsrudel 

Sorry this was a problem with the blueprint for the learn guide, Shipyard was trying to parse there markdown readme which was not a Shipyard readme containing front matter.

I have corrected this and given things a quick test and all seems ok now.

When you run things again you can use the following command `--force-update` to force shipyard to re-download the blueprint. This flag only needs set when you want to overwrite the cached blueprint and images.

```
shipyard run --force-update github.com/shipyard-run/blueprints//learn-consul-service-mesh
```
