### ISSUE TITLE
Color customisations in .vscode/settings.json

### ISSUE THREAD

**Issue by rebrendov** [shipyard-run/shipyard#67]
Hello! I use vscode with a custom dark theme, and when I open shipyard project for the first time it changed an Activity bar and a Status bar color. I think color settings for vscode can be safely rremoved from .vscode/settings.json.

**Comment by nicholasjackson** [comment]
Thanks, I must have checked that in by accident. Thank you also for your other PR, I was refactoring that code the other day and introduced that bug :)
