### ISSUE TITLE
add support for scripted health checks

### ISSUE THREAD

**Issue by ksatirli** [shipyard-run/shipyard#82]
Shipyard currently supports HTTP health checks that require an endpoint to respond with `200 - OK`.

For use-cases such as an uninitialized Vault server, the `health` endpoint responds with a non-200 code, despite the server being "up" (though not "available", as it would be uninitialized, and possibly sealed).

I'd love to see support for scripted health checks that allow me to pass in a shell script that can do multiple checks that I consider "sufficient" to mark a container as healthy.

**Comment by ksatirli** [comment]
One other approach I've been thinking of is staged health checks, along the following lines:

```javascript
health_check {
  stage "init" {
    timeout    = "30s"
    http       = "http://localhost:8200/v1/sys/health?uninitcode=200" 
 }

 stage "unseal" {
    depends_on = "health_check.stage.init"
    timeout    = "30s"
    http       = "http://localhost:8200/v1/sys//sys/seal-status" 
   contains    = "\"sealed\": false,"
 }
}
```

In this example, Shipyard would run the `init` check first, if this is successful, it would continue with the `unseal` healthcheck. Only if both report "ok" will the container be considered healthy.

The `depends_on` in the second stage is meant to limit it from executing _only_ when the first check has passed.

I fully realize that this is much more complicated than exposing an option to run a shell script, but I wanted to share my thoughts for discussion.

**Comment by devops-rob** [comment]
Just to add to this usecase, if a vault instance were to be in a healthy standby state, it returns a 429

**Comment by nicholasjackson** [comment]
I have added a PR to update this issue, I think staged health checks over-complicate the configuration, ultimately all really need is that the final stage passes and the dependencies can be created.

The PR adds support for an optional array of HTTP status codes, that will satisfy the Vault use case, however, I would argue that the Vault Health Check API is not RESTful and misuses HTTP status codes.  That said Shipyard needs to enable all cases and this PR should do that.

Ideally, the status codes should be encapsulated into a block but this would then break configuration, we were originally trying to keeps this as simple as possible hence the simple types. Will probably need to revisit this at some point in the future.
