### ISSUE TITLE
How to expose docker container port in shipyard to outside of docker

### ISSUE THREAD

**Issue by mehdihadeli** [shipyard-run/shipyard#86]
Hi,
I want to expose my docker container port in shipyard to outside of docker, how can I do that?

**Comment by eveld** [comment]
Hello,

To expose a container to your machine you can use an ingress e.g. https://github.com/shipyard-run/blueprints/blob/main/consul-docker/ingress.hcl#L1

**Comment by mehdihadeli** [comment]
@eveld Ok Thanks.
But I use this way and it works.

```
container "api1" {
    image {
        name = "nicholasjackson/fake-service:v0.8.0"
    }
     port {
	    local = "9090"
		host = "9091"
		remote = "9091"
	 }
    env {
        key = "NAME"
        value = "API 1"
    }
}
```
