### ISSUE TITLE
nomad_ingress: host port is ignored

### ISSUE THREAD

**Issue by marvreichmann** [shipyard-run/shipyard#87]
I run Shipyard for MacOS installed via brew.

I define a nomad ingress like this:

```
nomad_ingress "nomad-http" {
  cluster = "nomad_cluster.dev"
  job     = ""
  group   = ""
  task    = ""

  port {
    local           = 4646
    remote          = 4646
    host            = 14646
    open_in_browser = "/"
  }

  network {
    name = "network.cloud"
  }
}
```
but the assigned port for host in docker is something like 64682.

what am i doing wrong?

**Comment by eveld** [comment]
Hello, that syntax looks correct. Do you perhaps have some more information such as OS and the blueprint that you are running?

**Comment by marvreichmann** [comment]
I tried running some example blueprints from the official repo. some things did in fact work, eg. consul, but for whatever reason nomad won't adopt the correct port. I tried reducing the blueprints to the minimum required to run nomad. But that did not solve my problem.

I run MacOS Catalina 10.15.7. I installed shipyard via brew. 

I tried tearing down and restarting the whole setup multiple times and also cleared out my docker setup during the process, to mitigate any potential issues with residual containers or cached images and the like. That also did nothing, i'm afraid.

Any more information i could provide?

**Comment by eveld** [comment]
@nicholasjackson could you double check if the Nomad Ingress works on OSX? This might be a Docker Desktop/Machine kind of issue :/

**Comment by nicholasjackson** [comment]
@marvreichmann sorry for the delay I will test this in the morning, I need to rebuild my mac.

**Comment by nicholasjackson** [comment]
@marvreichmann I have been testing this, unfortunately, the ingress is not working, I think the recent updates to Nomad networking have broken this. I am working on a fix, should be out tonight I hope.
.

**Comment by nicholasjackson** [comment]
Status update on this issue. We have rebuilt the ingress to correctly infer the IP and port from the Nomad cluster, need to do a little work to update the nomad config and ingress resource but this is nearly there. 

https://github.com/shipyard-run/ingress/pulls

**Comment by nicholasjackson** [comment]
@marvreichmann Thanks for reporting this issue, I think this should now be fixed, I have also updated the docs for Nomad Ingress.

https://shipyard.run/docs/resources/nomad_ingress

I will do a release in an hour or so as soon as I finish dinner.

Nic

**Comment by marvreichmann** [comment]
@nicholasjackson Great, thank you for the quick fix. I will check it out some time this weekend. Enjoy your dinner!
